<a href="https://colab.research.google.com/github/official-okello/DS_bootcamp_with_gomycode/blob/master/Data_pre_processing_checkpoint.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Load the dataset, display the ten first lines, store the results in a variable called 'client_0_bills'.
# What is the data type of the 'client_0_bills' variable ?
# Display the general information of the dataset and try to answer the following questions :
# How many rows and columns do we have in this dataset ?
# How many categorical features are present in the dataset ?
# How much memory space does the dataset consume ?
# Inspect the dataset for potential missing values.
# Select your strategy to handle missing values, and tell us why you had made that choice.
# Run a descriptive analysis on numeric features (columns).
# Select the bills records for the client with an id ='train_Client_0', using 2 methods.
# Transform the 'counter_type' feature to a numeric variable using the encoder of your choice.
# Delete the 'counter_statue' feature from the Dataframe

In [2]:
import pandas as pd
import numpy as np

In [6]:
dataset = pd.read_csv('/content/STEG_BILLING_HISTORY.csv', low_memory=False)
client_0_bills = dataset.head(10)
print(type(client_0_bills))

<class 'pandas.core.frame.DataFrame'>

In [11]:
#number of rows and columns
dataset.shape

(4476749, 16)

In [12]:
#categorical features present in the dataset
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4476749 entries, 0 to 4476748
Data columns (total 16 columns):
 #   Column                Dtype
---  ------                -----
 0   client_id             object
 1   invoice_date          object
 2   tarif_type            int64
 3   counter_number        float64
 4   counter_statue        object
 5   counter_code          int64
 6   reading_remarque      float64
 7   counter_coefficient   int64
 8   consommation_level_1  int64
 9   consommation_level_2  int64
 10  consommation_level_3  int64
 11  consommation_level_4  int64
 12  old_index             int64
 13  new_index             int64
 14  months_number         int64
 15  counter_type          object
dtypes: float64(2), int64(10), object(4)
memory usage: 546.5+ MB

In [13]:
# memory space does the dataset consume
dataset.memory_usage()

Index                        132
client_id               35813992
invoice_date            35813992
tarif_type              35813992
counter_number          35813992
counter_statue          35813992
counter_code            35813992
reading_remarque        35813992
counter_coefficient     35813992
consommation_level_1    35813992
consommation_level_2    35813992
consommation_level_3    35813992
consommation_level_4    35813992
old_index               35813992
new_index               35813992
months_number           35813992
counter_type            35813992
dtype: int64

In [14]:
#dataset for potential missing values
dataset.isnull().sum()

client_id                  0
invoice_date               0
tarif_type                 0
counter_number            48
counter_statue             0
counter_code               0
reading_remarque        4531
counter_coefficient        0
consommation_level_1       0
consommation_level_2       0
consommation_level_3       0
consommation_level_4       0
old_index                  0
new_index                  0
months_number              0
counter_type               0
dtype: int64

In [11]:
#handling missing values
# dataset.fillna(0, inplace=True)
dataset.fillna(dataset.mode(), inplace=True)
client_0_bills

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,2014-03-24,11,1335667.0,0,203,8.0,1,82.0,0.0,0.0,0.0,14302.0,14384.0,4.0,ELEC
1,train_Client_0,2013-03-29,11,1335667.0,0,203,6.0,1,1200.0,184.0,0.0,0.0,12294.0,13678.0,4.0,ELEC
2,train_Client_0,2015-03-23,11,1335667.0,0,203,8.0,1,123.0,0.0,0.0,0.0,14624.0,14747.0,4.0,ELEC
3,train_Client_0,2015-07-13,11,1335667.0,0,207,8.0,1,102.0,0.0,0.0,0.0,14747.0,14849.0,4.0,ELEC
4,train_Client_0,2016-11-17,11,1335667.0,0,207,9.0,1,572.0,0.0,0.0,0.0,15066.0,15638.0,12.0,ELEC
5,train_Client_0,2017-07-17,11,1335667.0,0,207,9.0,1,314.0,0.0,0.0,0.0,15638.0,15952.0,8.0,ELEC
6,train_Client_0,2018-12-07,11,1335667.0,0,207,9.0,1,541.0,0.0,0.0,0.0,15952.0,16493.0,12.0,ELEC
7,train_Client_0,2019-03-19,11,1335667.0,0,207,9.0,1,585.0,0.0,0.0,0.0,16493.0,17078.0,8.0,ELEC
8,train_Client_0,2011-07-22,11,1335667.0,0,203,9.0,1,1200.0,186.0,0.0,0.0,7770.0,9156.0,4.0,ELEC
9,train_Client_0,2011-11-22,11,1335667.0,0,203,6.0,1,1082.0,0.0,0.0,0.0,9156.0,10238.0,4.0,ELEC

In [14]:
# descriptive analysis on numeric features (columns)
dataset.describe()

,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number
count,334819.000000,3.348190e+05,334819.000000,334819.000000,334819.000000,334819.000000,334819.000000,334819.000000,334819.000000,334819.000000,3.348190e+05,3.348190e+05,334819.000000
mean,20.145577,1.106011e+11,0.040942,171.538763,7.310457,1.000024,403.716847,109.275919,20.091927,55.576040,1.768343e+04,1.823236e+04,21.568220
std,13.471341,1.564632e+12,0.369176,133.036493,1.359816,0.016212,576.859616,933.113019,219.142658,1216.133149,4.481928e+04,4.543935e+04,929.117173
min,8.000000,0.000000e+00,0.000000,5.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,1.000000
25%,11.000000,1.221580e+05,0.000000,5.000000,6.000000,1.000000,78.000000,0.000000,0.000000,0.000000,1.765000e+03,2.031000e+03,4.000000
50%,11.000000,4.946870e+05,0.000000,203.000000,6.000000,1.000000,269.000000,0.000000,0.000000,0.000000,7.524000e+03,8.017000e+03,4.000000
75%,40.000000,1.136139e+06,0.000000,207.000000,9.000000,1.000000,598.000000,0.000000,0.000000,0.000000,2.132000e+04,2.200450e+04,4.000000
max,45.000000,2.738110e+13,5.000000,600.000000,9.000000,10.000000,93385.000000,209952.000000,45360.000000,343568.000000,2.800280e+06,2.870972e+06,99104.000000

In [21]:
# Select the bills records for the client with an id ='train_Client_0', using 2 methods.
dataset.loc[dataset['client_id'] == 'train_Client_0'] #Using loc
index_positions = dataset.index[dataset['client_id'] == 'train_Client_0'] #using iloc
dataset.iloc[index_positions]

         client_id invoice_date  tarif_type  counter_number  counter_statue  \
0   train_Client_0   2014-03-24          11       1335667.0               0
1   train_Client_0   2013-03-29          11       1335667.0               0
2   train_Client_0   2015-03-23          11       1335667.0               0
3   train_Client_0   2015-07-13          11       1335667.0               0
4   train_Client_0   2016-11-17          11       1335667.0               0
5   train_Client_0   2017-07-17          11       1335667.0               0
6   train_Client_0   2018-12-07          11       1335667.0               0
7   train_Client_0   2019-03-19          11       1335667.0               0
8   train_Client_0   2011-07-22          11       1335667.0               0
9   train_Client_0   2011-11-22          11       1335667.0               0
10  train_Client_0   2008-11-25          11       1335667.0               0
11  train_Client_0   2012-07-23          11       1335667.0               0
12  train_Client_0   2012-11-29          11       1335667.0               0
13  train_Client_0   2013-07-22          11       1335667.0               0
14  train_Client_0   2014-07-18          11       1335667.0               0
15  train_Client_0   2014-11-24          11       1335667.0               0
16  train_Client_0   2015-11-18          11       1335667.0               0
17  train_Client_0   2012-03-27          11       1335667.0               0
18  train_Client_0   2011-03-30          11       1335667.0               0
19  train_Client_0   2013-02-12          11       1335667.0               0
20  train_Client_0   2010-07-22          11       1335667.0               0
21  train_Client_0   2010-11-24          11       1335667.0               0
22  train_Client_0   2005-10-17          11       1335667.0               0
23  train_Client_0   2006-02-24          11       1335667.0               0
24  train_Client_0   2006-06-23          11       1335667.0               0
25  train_Client_0   2006-10-18          11       1335667.0               0
26  train_Client_0   2007-06-27          11       1335667.0               0
27  train_Client_0   2007-10-25          11       1335667.0               0
28  train_Client_0   2007-02-26          11       1335667.0               0
29  train_Client_0   2008-07-28          11       1335667.0               0
30  train_Client_0   2009-01-04          11       1335667.0               0
31  train_Client_0   2009-07-27          11       1335667.0               0
32  train_Client_0   2009-11-24          11       1335667.0               0
33  train_Client_0   2010-03-29          11       1335667.0               0
34  train_Client_0   2008-01-04          11       1335667.0               0

    counter_code  reading_remarque  counter_coefficient  consommation_level_1  \
0            203               8.0                    1                  82.0
1            203               6.0                    1                1200.0
2            203               8.0                    1                 123.0
3            207               8.0                    1                 102.0
4            207               9.0                    1                 572.0
5            207               9.0                    1                 314.0
6            207               9.0                    1                 541.0
7            207               9.0                    1                 585.0
8            203               9.0                    1                1200.0
9            203               6.0                    1                1082.0
10           203               6.0                    1                 174.0
11           203               6.0                    1                 628.0
12           203               6.0                    1                 886.0
13           203               8.0                    1                 147.0
14           203               8.0                    1                  99.0
15           203               8.0                    1                 141.0
16           207               9.0                    1                 217.0
17           203               8.0                    1                 292.0
18           203               6.0                    1                 497.0
19           203               8.0                    1                  38.0
20           203               6.0                    1                 278.0
21           203               6.0                    1                 234.0
22           203               6.0                    1                 124.0
23           203               6.0                    1                 141.0
24           203               6.0                    1                 162.0
25           203               6.0                    1                 159.0
26           203               6.0                    1                 240.0
27           203               6.0                    1                 276.0
28           203               6.0                    1                 182.0
29           203               6.0                    1                 171.0
30           203               6.0                    1                 315.0
31           203               6.0                    1                 312.0
32           203               6.0                    1                 267.0
33           203               6.0                    1                 276.0
34           203               6.0                    1                 277.0

    consommation_level_2  consommation_level_3  consommation_level_4  \
0                    0.0                   0.0                   0.0
1                  184.0                   0.0                   0.0
2                    0.0                   0.0                   0.0
3                    0.0                   0.0                   0.0
4                    0.0                   0.0                   0.0
5                    0.0                   0.0                   0.0
6                    0.0                   0.0                   0.0
7                    0.0                   0.0                   0.0
8                  186.0                   0.0                   0.0
9                    0.0                   0.0                   0.0
10                   0.0                   0.0                   0.0
11                   0.0                   0.0                   0.0
12                   0.0                   0.0                   0.0
13                   0.0                   0.0                   0.0
14                   0.0                   0.0                   0.0
15                   0.0                   0.0                   0.0
16                   0.0                   0.0                   0.0
17                   0.0                   0.0                   0.0
18                   0.0                   0.0                   0.0
19                   0.0                   0.0                   0.0
20                   0.0                   0.0                   0.0
21                   0.0                   0.0                   0.0
22                   0.0                   0.0                   0.0
23                   0.0                   0.0                   0.0
24                   0.0                   0.0                   0.0
25                   0.0                   0.0                   0.0
26                   0.0                   0.0                   0.0
27                   0.0                   0.0                   0.0
28                   0.0                   0.0                   0.0
29                   0.0                   0.0                   0.0
30                   0.0                   0.0                   0.0
31                   0.0                   0.0                   0.0
32                   0.0                   0.0                   0.0
33                   0.0                   0.0                   0.0
34                   0.0                   0.0                   0.0

    old_index  new_index  months_number counter_type
0     14302.0    14384.0            4.0         ELEC
1     12294.0    13678.0            4.0         ELEC
2     14624.0    14747.0            4.0         ELEC
3     14747.0    14849.0            4.0         ELEC
4     15066.0    15638.0           12.0         ELEC
5     15638.0    15952.0            8.0         ELEC
6     15952.0    16493.0           12.0         ELEC
7     16493.0    17078.0            8.0         ELEC
8      7770.0     9156.0            4.0         ELEC
9      9156.0    10238.0            4.0         ELEC
10     5417.0     5591.0            4.0         ELEC
11    10780.0    11408.0            4.0         ELEC
12    11408.0    12294.0            4.0         ELEC
13    13983.0    14130.0            4.0         ELEC
14    14384.0    14483.0            4.0         ELEC
15    14483.0    14624.0            4.0         ELEC
16    14849.0    15066.0            4.0         ELEC
17    10488.0    10780.0            4.0         ELEC
18     7273.0     7770.0            4.0         ELEC
19    14264.0    14302.0            2.0         ELEC
20     6761.0     7039.0            4.0         ELEC
21     7039.0     7273.0            4.0         ELEC
22     3685.0     3809.0            4.0         ELEC
23     3809.0     3950.0            4.0         ELEC
24     3950.0     4112.0            4.0         ELEC
25     4112.0     4271.0            4.0         ELEC
26     4453.0     4693.0            4.0         ELEC
27     4693.0     4969.0            4.0         ELEC
28     4271.0     4453.0            4.0         ELEC
29     5246.0     5417.0            4.0         ELEC
30     5591.0     5906.0            4.0         ELEC
31     5906.0     6218.0            4.0         ELEC
32     6218.0     6485.0            4.0         ELEC
33     6485.0     6761.0            4.0         ELEC
34     4969.0     5246.0            4.0         ELEC

In [23]:
# Transform the 'counter_type' feature to a numeric variable using the encoder of your choice.
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset['counter_type'] = le.fit_transform(dataset['counter_type'])
dataset.head()

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,2014-03-24,11,1335667.0,0,203,8.0,1,82.0,0.0,0.0,0.0,14302.0,14384.0,4.0,0
1,train_Client_0,2013-03-29,11,1335667.0,0,203,6.0,1,1200.0,184.0,0.0,0.0,12294.0,13678.0,4.0,0
2,train_Client_0,2015-03-23,11,1335667.0,0,203,8.0,1,123.0,0.0,0.0,0.0,14624.0,14747.0,4.0,0
3,train_Client_0,2015-07-13,11,1335667.0,0,207,8.0,1,102.0,0.0,0.0,0.0,14747.0,14849.0,4.0,0
4,train_Client_0,2016-11-17,11,1335667.0,0,207,9.0,1,572.0,0.0,0.0,0.0,15066.0,15638.0,12.0,0

In [24]:
# Delete the 'counter_statue' feature from the Dataframe
dataset.drop('counter_statue', axis=1, inplace=True)
dataset.head()

,client_id,invoice_date,tarif_type,counter_number,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,2014-03-24,11,1335667.0,203,8.0,1,82.0,0.0,0.0,0.0,14302.0,14384.0,4.0,0
1,train_Client_0,2013-03-29,11,1335667.0,203,6.0,1,1200.0,184.0,0.0,0.0,12294.0,13678.0,4.0,0
2,train_Client_0,2015-03-23,11,1335667.0,203,8.0,1,123.0,0.0,0.0,0.0,14624.0,14747.0,4.0,0
3,train_Client_0,2015-07-13,11,1335667.0,207,8.0,1,102.0,0.0,0.0,0.0,14747.0,14849.0,4.0,0
4,train_Client_0,2016-11-17,11,1335667.0,207,9.0,1,572.0,0.0,0.0,0.0,15066.0,15638.0,12.0,0